AWSTemplateFormatVersion: "2010-09-09"
Description: "Instancias EC2 para Apache, MySQL y Monitoreo - proyectoGrafana"

Parameters:
  KeyName:
    Type: String
    Description: "Nombre de la clave SSH para acceder a las instancias"

Resources:

  EC2Apache:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0
      KeyName: !Ref KeyName
      SubnetId: !ImportValue proyectoGrafana-SubnetPublic-ID
      SecurityGroupIds:
        - !ImportValue proyectoGrafana-SG-Apache-ID
      PrivateIpAddress: 172.20.1.50
      Tags:
        - Key: Name
          Value: "proyectoGrafana-apache"

  EC2Monitoreo:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0
      KeyName: !Ref KeyName
      SubnetId: !ImportValue proyectoGrafana-SubnetPublic-ID
      SecurityGroupIds:
        - !ImportValue proyectoGrafana-SG-Monitoreo-ID
      PrivateIpAddress: 172.20.1.100
      Tags:
        - Key: Name
          Value: "proyectoGrafana-monitoreo"

  EC2BD:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0
      KeyName: !Ref KeyName
      SubnetId: !ImportValue proyectoGrafana-SubnetPrivate-ID
      SecurityGroupIds:
        - !ImportValue proyectoGrafana-SG-BD-ID
      PrivateIpAddress: 172.20.2.10
      Tags:
        - Key: Name
          Value: "proyectoGrafana-bd"




Outputs:

  EC2ApacheID:
    Description: "ID de la instancia Apache"
    Value: !Ref EC2Apache
    Export:
      Name: "proyectoGrafana-EC2-Apache-ID"

  EC2BDID:
    Description: "ID de la instancia de Base de Datos"
    Value: !Ref EC2BD
    Export:
      Name: "proyectoGrafana-EC2-BD-ID"

  EC2MonitoreoID:
    Description: "ID de la instancia de Monitoreo"
    Value: !Ref EC2Monitoreo
    Export:
      Name: "proyectoGrafana-EC2-Monitoreo-ID"
