AWSTemplateFormatVersion: "2010-09-09"
Description: "Instancias EC2 para Apache, MySQL y Monitoreo - proyectoGrafana"

Parameters:
  KeyName:
    Type: String
    Description: "Nombre de la clave SSH para acceder a las instancias"

Resources:

  EC2Apache:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0
      KeyName: !Ref KeyName
      SubnetId: !ImportValue proyectoGrafana-SubnetPublic-ID
      SecurityGroupIds:
        - !ImportValue proyectoGrafana-SG-Apache-ID
      PrivateIpAddress: 172.20.1.50
      Tags:
        - Key: Name
          Value: "proyectoGrafana-apache"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y 
          sudo git clone https://github.com/pablomediavillamesa/proyectoGrafana.git
          sudo cp -r proyectoGrafana/Servidor-juegos ~/servidor-juegos
          sudo chmod +x ~/servidor-juegos/despliegue-juegos.sh
          sudo ~/servidor-juegos/despliegue-juegos.sh

  EC2Monitoreo:
    Type: AWS::EC2::Instance
    DependsOn:
      - EC2Apache
      - EC2BD
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0
      KeyName: !Ref KeyName
      SubnetId: !ImportValue proyectoGrafana-SubnetPublic-ID
      SecurityGroupIds:
        - !ImportValue proyectoGrafana-SG-Monitoreo-ID
      PrivateIpAddress: 172.20.1.100
      Tags:
        - Key: Name
          Value: "proyectoGrafana-monitoreo"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y 
          sudo git clone https://github.com/pablomediavillamesa/proyectoGrafana.git
          sudo cp -r proyectoGrafana/Servidor-monitor ~/servidor-monitor
          sudo chmod +x ~/servidor-monitor/despliegue-monitor.sh
          sudo ~/servidor-monitor/despliegue-monitor.sh


  EC2BD:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0
      KeyName: !Ref KeyName
      SubnetId: !ImportValue proyectoGrafana-SubnetPrivate-ID
      SecurityGroupIds:
        - !ImportValue proyectoGrafana-SG-BD-ID
      PrivateIpAddress: 172.20.2.10
      Tags:
        - Key: Name
          Value: "proyectoGrafana-bd"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y 
          sudo git clone https://github.com/pablomediavillamesa/proyectoGrafana.git
          sudo cp -r proyectoGrafana/Servidor-bd ~/servidor-bd
          sudo chmod +x ~/servidor-bd/install_configure_mysql.sh
          sudo ~/servidor_db/install_configure_mysql.sh

Outputs:

  EC2ApacheID:
    Description: "ID de la instancia Apache"
    Value: !Ref EC2Apache
    Export:
      Name: "proyectoGrafana-EC2-Apache-ID"

  EC2BDID:
    Description: "ID de la instancia de Base de Datos"
    Value: !Ref EC2BD
    Export:
      Name: "proyectoGrafana-EC2-BD-ID"

  EC2MonitoreoID:
    Description: "ID de la instancia de Monitoreo"
    Value: !Ref EC2Monitoreo
    Export:
      Name: "proyectoGrafana-EC2-Monitoreo-ID"
