AWSTemplateFormatVersion: "2010-09-09"
Description: "Instancias EC2 para Apache, MySQL y Monitoreo - proyectoGrafana"

Parameters:
  KeyName:
    Type: String
    Description: "Nombre de la clave SSH para acceder a las instancias"

Resources:

  EC2Apache:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0
      KeyName: !Ref KeyName
      SubnetId: !ImportValue proyectoGrafana-SubnetPublic-ID
      SecurityGroupIds:
        - !ImportValue proyectoGrafana-SG-Apache-ID
      PrivateIpAddress: 172.20.1.50
      Tags:
        - Key: Name
          Value: "proyectoGrafana-apache"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > /var/log/user-data.log 2>&1
          apt update -y
          apt install -y git
          touch /home/ubuntu/prueba1.txt
          echo "esto es un prueba" > /home/ubuntu/prueba1.txt
          chown ubuntu:ubuntu /home/ubuntu/prueba1.txt
          cd /home/ubuntu
          git clone https://github.com/pablomediavillamesa/proyectoGrafana.git
          cp -r proyectoGrafana/servidor-juegos servidor-juegos/
          cd servidor-juegos
          chmod +x despliegue-juegos.sh
          echo '@reboot root [ -f /etc/firstboot.done ] || ( /home/ubuntu/servidor-juegos/despliegue-juegos.sh && echo "finalizado" >> /home/ubuntu/prueba1.txt && touch /etc/firstboot.done )' > /etc/cron.d/deploy-once
          chmod 644 /etc/cron.d/deploy-once
          reboot

  EC2Monitoreo:
    Type: AWS::EC2::Instance
    DependsOn:
      - EC2Apache
      - EC2BD
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0
      KeyName: !Ref KeyName
      SubnetId: !ImportValue proyectoGrafana-SubnetPublic-ID
      SecurityGroupIds:
        - !ImportValue proyectoGrafana-SG-Monitoreo-ID
      PrivateIpAddress: 172.20.1.100
      Tags:
        - Key: Name
          Value: "proyectoGrafana-monitoreo"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > /var/log/user-data.log 2>&1
          apt update -y
          apt install -y git
          touch /home/ubuntu/prueba1.txt
          echo "esto es un prueba" > /home/ubuntu/prueba1.txt
          chown ubuntu:ubuntu /home/ubuntu/prueba1.txt
          cd /home/ubuntu
          git clone https://github.com/pablomediavillamesa/proyectoGrafana.git
          cp -r proyectoGrafana/servidor-monitor servidor-monitor/
          cd servidor-monitor
          chmod +x despliegue-monitor.sh
          echo '@reboot root [ -f /etc/firstboot.done ] || ( /home/ubuntu/servidor-monitor/despliegue-monitor.sh && echo "finalizado" >> /home/ubuntu/prueba1.txt && touch /etc/firstboot.done )' > /etc/cron.d/deploy-once
          chmod 644 /etc/cron.d/deploy-once
          reboot

  EC2BD:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0
      KeyName: !Ref KeyName
      SubnetId: !ImportValue proyectoGrafana-SubnetPrivate-ID
      SecurityGroupIds:
        - !ImportValue proyectoGrafana-SG-BD-ID
      PrivateIpAddress: 172.20.2.10
      Tags:
        - Key: Name
          Value: "proyectoGrafana-bd"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > /var/log/user-data.log 2>&1
          apt update -y
          apt install -y git
          touch /home/ubuntu/prueba1.txt
          echo "esto es un prueba" > /home/ubuntu/prueba1.txt
          cd /home/ubuntu
          git clone https://github.com/pablomediavillamesa/proyectoGrafana.git
          cp -r proyectoGrafana/Servidor-bd servidor-bd/
          cd servidor-bd
          chmod +x install_configure_mysql.sh
          ./install_configure_mysql.sh

Outputs:

  EC2ApacheID:
    Description: "ID de la instancia Apache"
    Value: !Ref EC2Apache
    Export:
      Name: "proyectoGrafana-EC2-Apache-ID"

  EC2BDID:
    Description: "ID de la instancia de Base de Datos"
    Value: !Ref EC2BD
    Export:
      Name: "proyectoGrafana-EC2-BD-ID"

  EC2MonitoreoID:
    Description: "ID de la instancia de Monitoreo"
    Value: !Ref EC2Monitoreo
    Export:
      Name: "proyectoGrafana-EC2-Monitoreo-ID"
