{
 "title": "Juegos Flappy y Fruit",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Juegos Iniciados",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(game_starts_total)" }
   ]
  },
  {
   "title": "Comparativa Partidas Flappy vs Fruit",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "game_starts_total", "legendFormat": "{{game}}" }
   ]
  },
  {
   "title": "Puntuación Máxima Flappy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_max_score{game=\"flappy\"}"
    }
   ]
  },
  {
   "title": "Puntuación Media Flappy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_avg_score{game=\"flappy\"}"
    }
   ]
  },
  {
   "title": "Likes por juego",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_likes_total{game=\"flappy\"}",
     "legendFormat": "Flappy Likes"
    },
    {
     "expr": "game_likes_total{game=\"fruit\"}",
     "legendFormat": "Fruit Slicer Likes"
    }
   ]
  },
  {
   "title": "Dislkes por juego",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_dislikes_total{game=\"flappy\"}",
     "legendFormat": "Flappy Dislikes"
    },
    {
     "expr": "game_dislikes_total{game=\"fruit\"}",
     "legendFormat": "Fruit Slicer Dislikes"
    }
   ]
  },
  {
   "title": "Puntuación Máxima Fruit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_max_score{game=\"fruit\"}"
    }
   ]
  },
  {
   "title": "Puntuación Media Fruit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_avg_score{game=\"fruit\"}"
    }
   ]
  },
  {
   "title": "Evolución Juegos Jugados",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 22 },
   "targets": [
    { "expr": "game_starts_total", "legendFormat": "{{game}}" }
   ]
  },
  {
   "title": "Likes Vs Dilikes Totales",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 7, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (game_likes_total)",
     "legendFormat": "Likes"
    },
    {
     "expr": "sum by(instance) (game_dislikes_total{instance=\"192.168.0.50\"})",
     "legendFormat": "Dislikes"
    }
   ]
  }
 ]
}