apiVersion: 1

datasources:
  - name: MySQL Monitoring
    type: mysql
    access: proxy
    url: 172.20.2.10:3306
    user: pablom
    database: monitoring
    isDefault: false
    secureJsonData:
      password: pablom
    jsonData:
      tlsSkipVerify: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.20.1.100:9090
    isDefault: true