global:
  scrape_interval: 5s  # Puedes dejarlo en 5s si prefieres detección más rápida

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '172.20.1.100:9093'  # Cambia esto si Alertmanager está en otro host/puerto

rule_files:
  - "/etc/prometheus/alert.rules.yml"  # Archivo donde están tus reglas como "NuevoRecordFruit"


scrape_configs:
  - job_name: 'monitoring-node'
    static_configs:
      - targets: ['172.20.1.100:9100']

  - job_name: 'apache-server'
    static_configs:
      - targets: ['172.20.1.50:9100']

  - job_name: 'tfg_php_metrics'
    metrics_path: '/metrics_export.php'
    scheme: http
    static_configs:
      - targets: ['172.20.1.50']

  - job_name: 'website_health'
    metrics_path: '/website.php'
    scheme: http
    static_configs:
      - targets: ['172.20.1.50']
