groups:

- name: website-health
  rules:
  - alert: WebsiteDown
    expr: absent(website_up)
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "⚠️ ¡La web no está disponible!"
      description: "No se puede acceder a website-health.php desde Prometheus."

- name: game_alerts
  rules:
    - alert: NewRecordFlappy
      expr: new_record{game="flappy"} > 0
      for: 0s   # Esperar 10 segundos para asegurar que la alerta es consistente
      labels:
        severity: critical
        alertname: "NewRecordFlappy"
        game: "flappy"
      annotations:
        summary: "🎮 ¡Nuevo récord en flappy!"
        description: "El nuevo récord en flappy es {{ $value }} puntos."

    - alert: NewRecordFruit
      expr: new_record{game="fruit"} > 0
      for: 0s
      labels:
        severity: critical
        alertname: "NewRecordFruit"
        game: "fruit"
      annotations:
        summary: "🎮 ¡Nuevo récord en fruit!"
        description: "El nuevo récord en fruit es {{ $value }} puntos."
