global:
  resolve_timeout: 30s

route:
  receiver: 'telegram'
  group_wait: 5s
  group_interval: 3m
  repeat_interval: 2m  # Repetir cada 2 minutos mientras esté FIRING

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '7204133505:AAGMdnip-eoRR9JEVYHlRWXYMhZzrqPpA_Q'
        chat_id: 5399941404
        parse_mode: 'Markdown'
        message: |
          {{ .CommonAnnotations.summary }}
          {{ .CommonAnnotations.description }}
