{
 "title": "Métricas Juegos",
 "description": "Panel de visualización de métricas de mi servidor web",
 "tags": [
  "apache",
  "prometheus",
  "alertmanager",
  "php",
  "json "
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Alertas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "New panel", "type": "alertlist", "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 } },
  { "title": "Gráficos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Partidas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "game_starts_total{game=\"flappy\"}",
     "legendFormat": "{{game}} "
    },
    {
     "expr": "game_starts_total{game=\"fruit\"}",
     "legendFormat": "{{game}} "
    }
   ]
  },
  {
   "title": "Likes Dislikes ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "game_likes_total", "legendFormat": "likes {{game}}" },
    { "expr": "game_dislikes_total", "legendFormat": "dislikes {{game}}" }
   ]
  },
  {
   "title": "Comparativa de partidas",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "game_starts_total", "legendFormat": "{{game}}" }
   ]
  },
  {
   "title": "Comparativa Puntuacion Flappy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "game_last_score{game=\"flappy\"}",
     "legendFormat": "ultima puntacion"
    },
    {
     "expr": "game_avg_score{game=\"flappy\"}",
     "legendFormat": "media de puntuacion"
    }
   ]
  },
  {
   "title": "Comparativa Puntuacion Fruit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "game_last_score{game=\"fruit\"}",
     "legendFormat": "ultima puntacion"
    },
    {
     "expr": "game_avg_score{game=\"flappy\"}",
     "legendFormat": "media de puntuacion"
    }
   ]
  },
  {
   "title": "Puntuaciones",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_last_score{game=\"flappy\"}",
     "legendFormat": "{{game}} ultima"
    },
    {
     "expr": "game_avg_score{game=\"flappy\"}",
     "legendFormat": "{{game}} media"
    },
    {
     "expr": "game_max_score{game=\"flappy\"}",
     "legendFormat": "{{game}} maxima"
    }
   ]
  },
  {
   "title": "Puntuaciones",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_last_score{game=\"fruit\"}",
     "legendFormat": "{{game}} ultima"
    },
    {
     "expr": "game_avg_score{game=\"fruit\"}",
     "legendFormat": "{{game}} media"
    },
    {
     "expr": "game_max_score{game=\"fruit\"}",
     "legendFormat": "{{game}} maxima"
    }
   ]
  },
  { "title": "Base de datos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Informacion sobre el sistema",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT 'version' AS parametro, @@version AS valor UNION ALL\r\nSELECT 'hostname', @@hostname UNION ALL\r\nSELECT 'datadir', @@datadir UNION ALL\r\nSELECT 'basedir', @@basedir UNION ALL\r\nSELECT 'port', @@port UNION ALL\r\nSELECT 'max_connections', @@max_connections UNION ALL\r\nSELECT 'table_open_cache', @@table_open_cache UNION ALL\r\nSELECT 'open_files_limit', @@open_files_limit UNION ALL\r\nSELECT 'innodb_buffer_pool_size', @@innodb_buffer_pool_size UNION ALL\r\nSELECT 'innodb_log_file_size', @@innodb_log_file_size UNION ALL\r\nSELECT 'innodb_log_buffer_size', @@innodb_log_buffer_size UNION ALL\r\nSELECT 'innodb_file_per_table', @@innodb_file_per_table UNION ALL\r\nSELECT 'tmp_table_size', @@tmp_table_size UNION ALL\r\nSELECT 'max_heap_table_size', @@max_heap_table_size UNION ALL\r\nSELECT 'wait_timeout', @@wait_timeout UNION ALL\r\nSELECT 'interactive_timeout', @@interactive_timeout UNION ALL\r\nSELECT 'sql_mode', @@sql_mode UNION ALL\r\nSELECT 'character_set_server', @@character_set_server UNION ALL\r\nSELECT 'collation_server', @@collation_server;\r\n"
    }
   ]
  },
  {
   "title": "Ultima insercciónn de datos en cada tabla",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT\r\n  'metrics' AS tabla,\r\n  MAX(event_time) AS ultima_insercion\r\nFROM metrics\r\nUNION ALL\r\nSELECT\r\n  'metrics_likes' AS tabla,\r\n  MAX(event_time) AS ultima_insercion\r\nFROM metrics_likes;\r\n"
    }
   ]
  },
  {
   "title": "Registros de cada tabla ",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT\r\n  table_name AS 'Tabla',\r\n  table_rows AS 'Registros'\r\nFROM\r\n  information_schema.TABLES\r\nWHERE\r\n  table_schema = 'monitoring';\r\n"
    }
   ]
  },
  {
   "title": "Puntuaciones Máximas históricas",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT\r\n  game,\r\n  score,\r\n  event_time\r\nFROM\r\n  (\r\n    SELECT\r\n      game,\r\n      score,\r\n      event_time,\r\n      ROW_NUMBER() OVER (PARTITION BY game ORDER BY score DESC, event_time DESC) AS rn\r\n    FROM\r\n      metrics\r\n    WHERE\r\n      event_type = 'score'\r\n  ) AS sub\r\nWHERE\r\n  rn <= 3\r\nORDER BY\r\n  game,\r\n  score DESC,\r\n  event_time DESC;\r\n"
    }
   ]
  },
  {
   "title": "Tamaño en MB de cada tabla",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT\r\n  table_name AS 'Tabla',\r\n  ROUND((data_length + index_length) / 1024 / 1024, 2) AS 'Tamaño (MB)'\r\nFROM\r\n  information_schema.TABLES\r\nWHERE\r\n  table_schema = 'monitoring'\r\nORDER BY\r\n  (data_length + index_length) DESC;\r\n"
    }
   ]
  }
 ]
}